services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./wp-db:/var/lib/mysql
    restart: always
    platform: '${PLATFORM:-default}'
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
  wordpress:
    # use wp-xdebug for wp with xdebug
    build:
      context: .
      dockerfile: wp.Dockerfile
    ports:
      - 80:80
    volumes:
#      - .:/var/www/html/wp-content/themes/{your_theme}
#      - ./.htaccess:/var/www/html/.htaccess
      - ./wp-html:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress